### ISSUE TITLE
APP findet keine Shellys im lokalen Netzwerk 

### ISSUE THREAD

**Issue by Qara2003** [digaus/shellyhome-i18n#10]
Hallo Dirk,

ich habe einiger Shelly 2.5, Shelly 1, Shelly PlugS sowie Shelly DW2 im Einsatz. Alle haben eine fixe IP im Netz. 192.168.2.1-192.168.2.254 255.255.255.0 und sind über Coap an einen IoBroker angeschaltet. 
Das Netzwerk besteht zu 100% aus AVM Router und Acces Points, alle auf aktuellem SW Stand. SSID ist sichtbar. Auf dem IPhone 8 habe ich die aktuelle SW von Apple. Bei allen Shellys habe ich die Cloud ausgeschaltet, alle waren aber mal angemeldet. 
Also ich starte deine APP und melde mich nicht in der Cloud an. Gehe auf Dashboard anlegen und dann auf Gerät hinzufügen. Dann kann ich den Shelly Typ aussuchen meine SSID wird schon korrekt angezeigt. Nach Eingabe des Passworts erscheint 
Verifying „SSID“ gelbes Dreieck mit Ausrufezeichen 
Connections to Shelly 1 ❌ 

Kann es an der Coap Einstellung liegen?

VG
Olli

**Comment by digaus** [comment]
Hallo Olli,

du bist im falschen Menü Punkt. Mit "Hinzufügen" kannst du Shellys welche noch nicht in deinem Netzwerk sind diesem hinzufügen...

Über "Geräte suchen" kannst du alle Geräte in deinem Netzwerk finden und hinzufügen.

Dort kannst du auch in den Einstellungen ggf. deinen IP Bereich anpassen.

MfG

**Comment by Qara2003** [comment]
Jepp. Habe die APP nochmal neu installiert. Jetzt wurde ich auch gefragt ob die APP das lokale Netzwerk nach Geräten durchsuchen darf. Und zack, alle Shellys da. 

Danke für die schnelle Rückmeldung. Ich mache das Ticket wieder zu. 

VG
Olli

**Comment by digaus** [comment]
@Qara2003 super, dass nun alles klappt.

Über eine angepasste Rezension würde ich mich natürlich freuen ;)

**Comment by Qara2003** [comment]
@digaus Hab ich schon erledigt 😀
