### ISSUE TITLE
Windows version download link

### ISSUE THREAD

**Issue by syper** [digaus/shellyhome-i18n#13]
the project mention **Shelly Home is available on Android, iOS, MacOS and Windows**
As it is such a nice tool on iOS, I would also like to see how is the windows version, where can I download it from?

**Comment by digaus** [comment]
> the project mention **Shelly Home is available on Android, iOS, MacOS and Windows** As it is such a nice tool on iOS, I would also like to see how is the windows version, where can I download it from?

I was waiting for a release of a dependency which I am using. Currently in the process of building the .exe. Will upload it here soon ;)

**Comment by syper** [comment]
Great, thanks :-)

**Comment by syper** [comment]
Release 2.0.7 for windows is great :D

- The only thing I did not like is to have to install it, but after installing I copied the folder to other place and uninstall and still working fine! **A portable version would be a great!!**

Other than that, just some minor things
- The zoom through the menu view works great, but from the built-in dashboard menu does not work
- When adding device to dashboard would be nice to have a search filed to filter so it's easier to find devices (and maybe sort them or show the belonging room)
- The settings are not sync with iOS... not sure technically if this is even possible, maybe with a shared folder for setting for iOS and Windows through google drive?!) (maybe this item is bad cost/benefit at least from the maintenance perspective or even security)

**Comment by digaus** [comment]
> 

Glad you like it.

-  Portable version is surely possible. Will upload zip later
-  Noticed that too. Will propably just remove zoom from the dashboard menu on Windows/MacOS
-  Will see if I can allow for Ctrl+F search
-  Syncing won't be added as I am not running a server (only connecting to Shelly Cloud). But you can export and import a backup from iOS to Windows

**Comment by syper** [comment]
Sounds perfect! 

For the searching I would juts add a textbox on top instead CTRL+F, but that just personal preference, any of those would do the trick anyhow!

**Comment by syper** [comment]
![image](https://user-images.githubusercontent.com/6415455/154651232-5c23c07c-cd63-414f-ad8c-7f9d886c4d42.png)

Darkmode is not consistent with the upper "windows" style frame!! not a major issue as the light theme is ok!

**Comment by syper** [comment]
The app hooks up in a strange way when called through a batch file...

I have tried all the following commands and it's always hooking to that command line windows and if I close the batchfile the app also closes as it looks they are hooked together... so strange...


 	    start "" "ShellyHome.exe"

 	REM start "" "ShellyHome.exe" /B

	REM start cmd /k "ShellyHome.exe && exit"
	
	REM start cmd /c "ShellyHome.exe"

	REM start "New Window" cmd /c "ShellyHome.exe"
	
	
![image](https://user-images.githubusercontent.com/6415455/154655149-cab37d11-3561-4ec2-81d8-d94d5b389906.png)
