### ISSUE TITLE
Kein Sync Shelly 1 Plus

### ISSUE THREAD

**Issue by Poilio92** [digaus/shellyhome-i18n#16]
Hallo, habe mehrere Shelly’s erfolgreich eingebunden nur der Shelly 1 Plus macht Probleme und lässt sich nicht verbinden. Er wird unter der Gerätesuche auch gefunden aber bleibt immer bei Sync hängen. Shelly wurde komplett zurückgesetzt und App neu installiert. Gibt es hier bekannte Probleme oder Lösungsvorschläge? Sonst ist die App echt top. Danke schonmal!

**Comment by digaus** [comment]
Shelly Plus Geräte sind noch vollständig integriert, da ich u.a. auch das Hinzufügen via Bluetooth hinzufügen möchte. Aktuell funktionieren die Plus und Pro Geräte nur via Cloud. D.h. wenn du diese mit der original Shelly App hinzugefügt hast kannst du in meiner App dies auch steuern sofern du angemeldet bist.

**Comment by Poilio92** [comment]
Danke für die schnelle Antwort. Dann weiß ich schonmal das es nicht an meinem Shelly liegt. Die Cloud kann ich leider nicht aktivieren da ich die Shelly’s per MQTT in ioBroker eingebunden habe. Soweit ich weiß funktioniert nur Cloud oder MQTT.

**Comment by digaus** [comment]
Shelly Plus und Pro können meines Wissens nach beides :)

**Comment by Poilio92** [comment]
Okay danke dann versuche ich das mal.

**Comment by mbehrle** [comment]
Besten Dank für die App! Da ich allerdings die Geräte genau nicht über die Cloud registrieren will, wäre die Unterstützung der Shelly Plus eine tolle und sehr willkommene Sache!

**Comment by digaus** [comment]
![image](https://user-images.githubusercontent.com/15358538/166111394-def5601d-bcc6-4a1b-8436-4124dfad44ae.png)

- [x] Status Shelly Plus/Pro via Polling abrufen
- [ ] Shelly Plus/Pro hinzufügen
- [ ] Status Shelly Plus/Pro via Websocket abrufen
- [ ] Shelly Plus/Pro Bluetooth-Integration (später)

**Comment by digaus** [comment]
Kleines Update, Beta ist für iOS verfügbar 😀

https://testflight.apple.com/join/CIp1CF71

**Comment by Poilio92** [comment]
Super, wird getestet 💪

**Comment by opa75** [comment]
Ich habe mir die App heruntergeladen, dann Geräte suchen, aber die App findet keine Geräte?
z.B. Shelly Plug S, Shelly 1, Shelly 1L, Shelly H+T, Shelly H+T plus usw..
Bitte um Info, was ich falsch mache.
Danke im Voraus

**Comment by digaus** [comment]
> . Shelly Plug S

Sind die Geräte mit dem WLAN verbunden? Werden diese von der original App gefunden? Android oder iOS?

Ist der korrekte IP Bereich eingetragen (nicht Pflicht aber hilft bei Problemen)

Mit freundlichen Grüßen

**Comment by opa75** [comment]
Danke für die prompte Reaktion.
Alle Shelly’s werden in der Shelly App angezeigt und können auch bedient werden.
Mfg

Fischergasse 12
5020 Salzburg

+43 699 1909 1885
________________________________
Von: digaus ***@***.***>
Gesendet: Thursday, September 29, 2022 4:35:57 PM
An: digaus/shellyhome-i18n ***@***.***>
Cc: opa75 ***@***.***>; Comment ***@***.***>
Betreff: Re: [digaus/shellyhome-i18n] Kein Sync Shelly 1 Plus (Issue #16)


. Shelly Plug S

Sind die Geräte mit dem WLAN verbunden? Werden diese von der original App gefunden? Android oder iOS?

Ist der korrekte IP Bereich eingetragen (nicht Pflicht aber hilft bei Problemen)

Mit freundlichen Grüßen

**Comment by digaus** [comment]
> Danke für die prompte Reaktion. Alle Shelly’s werden in der Shelly App angezeigt und können auch bedient werden. Mfg
> […](#)
> ________________________________ Von: digaus ***@***.***> Gesendet: Thursday, September 29, 2022 4:35:57 PM An: digaus/shellyhome-i18n ***@***.***> Cc: opa75 ***@***.***>; Comment ***@***.***> Betreff: Re: [digaus/shellyhome-i18n] Kein Sync Shelly 1 Plus (Issue #16) . Shelly Plug S Sind die Geräte mit dem WLAN verbunden? Werden diese von der original App gefunden? Android oder iOS? Ist der korrekte IP Bereich eingetragen (nicht Pflicht aber hilft bei Problemen) Mit freundlichen Grüßen — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdigaus%2Fshellyhome-i18n%2Fissues%2F16%23issuecomment-1262375533&data=05%7C01%7C%7C6fb22165d0f84bbc724208daa227ee23%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638000589628690041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2q4ROKYswL5%2BPP%2FXHqlq7iPkz6ZqiysWzKUuxIyrpOw%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPYDONFO4R6VIO3SPX2UR7LWAWSM3ANCNFSM5UPBXY4Q&data=05%7C01%7C%7C6fb22165d0f84bbc724208daa227ee23%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638000589628690041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TzZR7RQ1l4AXBTPFynpW9o%2B%2FM8A7ug4LmK46VKGq2js%3D&reserved=0>. You are receiving this because you commented.Message ID: ***@***.***>

Befindest du dich im gleich Netzwerk?
Bist du in meiner App angemeldet?  -> falls ja sollten die Geräte alle schon da sein und du kannst Sie auf dem Dashboard platzieren
Und handelt es sich um die iOS oder Android Anwendung?

**Comment by opa75** [comment]
Ich habe 2 verschiedene Netzwerke und die Geräte werden in der Shelly App angezeigt.
Bin in der App angemeldet
IOS App

**Comment by opa75** [comment]
Habe die App gelöscht, neu installiert und angemeldet => die Geräte sind nun sichtbar.
Danke nochmals für die Unterstützung
