### ISSUE TITLE
Keine Erträge in den Raumüberschriften

### ISSUE THREAD

**Issue by Neoman65** [digaus/shellyhome-i18n#18]
Hi,
Dashboard, in den einzelnen Räumen werden nur Verbräuche als Summe alle Geräte
![27D293BE-BF6F-4E3F-96C6-29B42E3B4510](https://user-images.githubusercontent.com/99805748/173223791-0447f25a-2771-4b76-987a-e9aa7fc7c4a0.jpeg)
 rot angezeigt. Warum keine Erträge ?
Gruß
GS

**Comment by digaus** [comment]
Weil ich auf Summe Verbrauch > 0 prüfe. So weit hatte ich damals nicht gedacht^^

Werde es anpassen. Danke für den Hinweis👍🏻
