### ISSUE TITLE
Kann mit IOS App Shelly nicht einbinden

### ISSUE THREAD

**Issue by Uli30** [digaus/shellyhome-i18n#24]
Sehr geehrter Herr Gausmann,
Ich kann leider meinen Em3 nicht einbinden (siehe Bild).
Ich suche seit längerem nach einer App die es mir erlaubt, den überzähligenStrom meiner PV Anlage zu verwenden.
Dazu möchte ich meine Shelly’s verwenden. 
Der Em3 liefert das Ergebnis und der Schelly Dimmer soll dann den Überschuss an einen Verbraucher weitergeben.
Also 100 Watt Überschuss führt zu Einstellungen des Dimmers damit dieser 100 Watt abgibt.
Ist das mit Ihrer App möglich?
Viele Anwender suchen so eine App.
Wäre auch bereit etwas Auszugeben.
Über eine Antwort würde ich mich freuen.
Gruß 
Uli
![84CF733D-4B68-4A39-9166-F8220F154189](https://user-images.githubusercontent.com/109210491/178697340-9ca2e894-a866-440e-8615-167c53f95c4c.png)

**Comment by digaus** [comment]
> Sehr geehrter Herr Gausmann,
> Ich kann leider meinen Em3 nicht einbinden (siehe Bild).
> Ich suche seit längerem nach einer App die es mir erlaubt, den überzähligenStrom meiner PV Anlage zu verwenden.
> Dazu möchte ich meine Shelly’s verwenden.
> Der Em3 liefert das Ergebnis und der Schelly Dimmer soll dann den Überschuss an einen Verbraucher weitergeben.
> Also 100 Watt Überschuss führt zu Einstellungen des Dimmers damit dieser 100 Watt abgibt.
> Ist das mit Ihrer App möglich?
> Viele Anwender suchen so eine App.
> Wäre auch bereit etwas Auszugeben.
> Über eine Antwort würde ich mich freuen.
> Gruß
> Uli
> ![84CF733D-4B68-4A39-9166-F8220F154189](https://user-images.githubusercontent.com/109210491/178697340-9ca2e894-a866-440e-8615-167c53f95c4c.png)

Hallo,

das von ihnen angeführte Szenario ist so nicht mit meiner App möglich. Dafür müssten sie Home Assistant oder ähnliches nutzen.

Meine App ist lediglicSteuern und Verwlten der Shellys als Alternative zur original App gedacht.

Auf dem Bild ist zu erkennen, dass der Shelly mit einem Pin versehen wurde. D.h. Sie müssten in der App diese Zugangsdaten eingeben, um das Gerät zu verwenden.

**Comment by Uli30** [comment]
Wow! Vielen Dank für Ihre schnelle Antwort!
Pin ist eigentlich in der Shelly App ausgeschaltet.
Habe keinen PIN vergeben.
Ja, da gibt es was in Home Assistant. Ist aber aufwendig, da ich erst mal einen Rechner mit Linux benötige damit HA läuft.
Ich bin kein SW Spezialist. Deshalb suche ich nach einer einfachen Lösung.
Suche jemanden der mir eine Einfache Lösung anbietet.
Sehr viele PV Nutzer haben das Problem mit der Überproduktion und der Sinnvollen Anwendungen.
Nochmals vielen Dank 
Uli
