### ISSUE TITLE
Shelly Pro 1PM not found

### ISSUE THREAD

**Issue by rmayergfx** [digaus/shellyhome-i18n#27]
Device is online with internal IP and reachable via Cloud/Webpage. No Security is set. Latest Firmware was installed with official Shelly Cloud App.

Tried to Setup the device with out luck. Network Scan doesn´t find the device. Manually set the range smaller to xxx.xxx.xxx.50 - 51 as the device is fixed on 50. Still no communication.

Tried to go with Include Devices, There i Found Shelly 1 Pro PM (ShellyPro1PM) but no connect possible. Also the Naming is different as on the official Homepage and there is no image!

How can this be fixed? How can i add an matching image ?

Please use the official Device Names from https://shelly.cloud/ Homepage listed in the Products Section. 

IOS 15.6.1 with latest App Version 2.0.11

**Comment by digaus** [comment]
Hello,

thanks for the issue. Include devices is for adding the device to your WiFi network.

The names are directly taken from the official Shelly config (friendly_name and WiFi SSID prefix).

You might have a new revision which I have not yet included. Can you post the output of http://shellyip/shelly to verify this?

**Comment by rmayergfx** [comment]
Shelly Pro 1PM shows 3 selectable tabs, JSON, Rohdaten, Kopfzeilen.
Rohdaten:
{"name":"PV","id":"shellypro1pm-30c6f780be6c","mac":"30C6F780BE6C","model":"SPSW-201PE16EU","gen":2,"fw_id":"20220617-112029/0.10.3-g7c89a05","ver":"0.10.3","app":"Pro1PM","auth_en":false,"auth_domain":null}

**Comment by digaus** [comment]
Seems I was correct:

SPSW-201PE16EU is a new revision of the Pro and since it is currently unknown for the app it will not be listed. 

I have a branch where I already added the new revisions. Will release a new version soon where I also can add the new devices in this repo and download the config for it so I do not have to publish a new version every time they change the device model...

**Comment by digaus** [comment]
Should be fixed with new version. Now I display a message when I find an unknown device. Just send me the content and I will add it.
