### ISSUE TITLE
Übertragung auf andere Geräte

### ISSUE THREAD

**Issue by managedata1** [digaus/shellyhome-i18n#28]
Hallo,
die App funktioniert sehr gut! Gibt es eine Möglichkeit, die Daten der Shellys (ohne Cloud) von einem Gerät auf andere Geräte zu übertragen?
Unter IOS kann ich zwar ein Backup machen, aber wie kann ich das Backup z.B. auf einem anderen Android-Gerät laden?

Gruß
Herbert Schulz

**Comment by digaus** [comment]
Einfach das Backup per Mail o.ä. teilen und dann auf dem Android Handy importieren.
