### ISSUE TITLE
App zeigt Verlauf des Stromverbrauchs nicht an

### ISSUE THREAD

**Issue by eazy2k13** [digaus/shellyhome-i18n#30]
Hallo zusammen,

ich habe mir einen Shelly Plug zugelegt um den Stromverbrauch von Geräten über einen längeren Zeitraum zu messen.
Die Einrichtung hat auch geklappt.
In der Shelly-Home-App werden jedoch keine Verlaufsdaten angezeigt, sondern nur der aktuelle Verbrauch.
Wenn möglich, möchte ich ohne ein Online-Konto auskommen.
![BF1AD3D7-647D-4025-A917-BACCA3907772](https://user-images.githubusercontent.com/6241589/196033577-ae021de6-50e8-48ba-b587-cfccc727fa6d.jpeg)

In der App wird immer nur „Daten konnten nicht geladen werden“ angezeigt.
Wie kann ich das denn beheben?

Vielen Dank,
eazy

**Comment by digaus** [comment]
Hallo,

für den Verlauf wird ein Shelly Konto benötigt. Der Shelly speichert selber keine Verkaufsdaten, deshalb kann ich den Graphen nur über die Shelly Cloud abfragen.

MfG

**Comment by eazy2k13** [comment]
Danke. Das ist die Lösung.
