### ISSUE TITLE
Bildschirm bleibt weiss

### ISSUE THREAD

**Issue by maxbrunold** [digaus/shellyhome-i18n#33]
Hallo Herr Gausmann,
seit einigen Tagen bleibt der Bildschirm meines iPhone einfach weiss (es erscheint nichts am Schirm), wenn ich die shelly-home App öffne. Dadurch habe ich die Kontrolle über meine Shellys verloren....  :-/
Ich habe das iPhone neu gestartet, das hat nicht geholfen.
Danach habe ich die App gelöscht und aus dem AppStore neu installiert. Aber auch das hat nichts gebracht, der Bildschirm bleibt weiss, wenn ich die App öffne...
Haben Sie eine Idee zu diesem Problem?
Mein iPhone ist ein iPhone SE 2020 kit iOS 14.3
Mit freundlichen Grüßen,
Max Brunold

**Comment by digaus** [comment]
Hallo Herr Brunold,

dazu erstmal die Frage warum nur iOS 14.3 genutzt wird? 

Die aktuellste 14er Version wäre hier 14.8.1

Ebenso sollte das iPhone SE auch mit iOS 16 funktionieren.

Ich würde daher vorschlagen zunächst einmal das iPhone zu aktualisieren.

MfG

**Comment by digaus** [comment]
Dennoch vielen Dank für die Info.

Ich denke ich habe auch eine Lösung für die älteren Versionen gefunden. Werde es demnächst testen und ein Update einspielen.

MfG

**Comment by maxbrunold** [comment]
Vielen Dank für die rasche Antwort.

Ja, ich habe eine veraltete Version von iOS auf meinem iPhone. Ich bin kein "early adopter" und Apple erlaubt es leider nicht, schrittweise Updates zu machen. So kann ich leider nicht auf 14.8.1 updaten, sondern musste gleich auf 16.4.1 gehen. Dieser Sprung erscheint mir auf den ersten Blick zu heftig.

Ich mache Updates meist nur dann, wenn es nicht anders geht, ich also quasi gezwungen bin (securtity-updates sind davon ausgenommen), da die neuen Versionen meist auch neue Probleme mit sich bringen, vor allem bei den "Nuller"-Versionen sind meist noch Bugs drinnen...  ...bzw. ändert sich oft auch die Bedienung und/oder es gibt "neue Funktionen", die ich meist gar nicht benötige (was die Komplexität durchaus erhöhen kann). Warum es Apple nicht erlaubt schrittweise vorzugehen (z.B. 14.3 -> 14.8.1 und dann auf 15.x oder so), das ist mir nicht klar.

Unter macOS habe ich bei meinem Kunden immer diese schrittweisen Updates gemacht, da so leichter zu überblicken war wann "das Ziel erreicht" war bzw. die Schritte und Umstellungen für den Kunden erträglicher waren. Bei iOS geht das leider aber nicht.... 

Wenn es eine Lösung für mein Problem mit Ihrer App gibt, dann wäre ich sehr dankbar.

Mit freundlichen Grüßen,
Max Brunold

**Comment by maxbrunold** [comment]
supported your work by giving a donation just a few minutes ago. :-) Thx

**Comment by digaus** [comment]
Vielen Dank dafür :) 

Geplant ist eine neue Version für diese Woche. Allerdings wollte ich zunächst noch Bluetooth Handling mit einbauen, um neue Geräte (Plus/Pro/BLU) einfacher hinzufügen zu können. Bin auch am überlegen, ob ich die Steuerung der Geräte via BT erlaube, falls mal das WLAN ausfällt. Aber denke, das werde ich in einem späteren Schritt umsetzen.

MfG

**Comment by maxbrunold** [comment]
Gibt es in dieser Sache etwas Neues? Würde mich sehr freuen....

Mit freundlichen Grüßen,
Max Brunold.

**Comment by maxbrunold** [comment]
Gibt's eine Chance auf ein Update? Ich wäre sehr dankbar......   :-)

LG,
Max.

**Comment by digaus** [comment]
Hallo Max,

Beta ist seit einigen Tagen verfügbar:

https://testflight.apple.com/join/CIp1CF71

Wollte diese demnächst freigeben. Wenn du zuvor testest wäre es natürlich noch besser.

MfG

**Comment by digaus** [comment]
@maxbrunold 
Konntest du schon testen?

MfG

**Comment by maxbrunold** [comment]
Ich habe die Beta-Version installiert auf meinem iPhone und sie lässt sich auch starten. Bin noch nicht zu einem ausreichenden Test gekommen, eines meiner shelly wird nicht gefunden, ich weiß aber nicht, ob das an der App liegt oder meinem WLAN oder dem shelly. Melde mich asap. Danke!

LG,
Max.

**Comment by maxbrunold** [comment]
Ich konnte meine 4 Shellys nun finden und sie werden unter "vorhandene Geräte" angezeigt.
Wenn ich versuche sie zur Kategorie "Geräte" hinzuzufügen, dann habe ich aber nur die Option "Räume". Die Aufklappliste bleibt rot und "Geräte" wird nicht als Option angezeigt. Ich würde die Shells aber gerne der Kategorie "Geräte" hinzufügen. Mache ich etwas falsch?
Beim "Modus" kann ich nur "Schalter" wählen, weitere Optionen werden nicht angezeigt. Bei "Typ" habe ich die Auswahl "Licht" oder "Steckdose".
Einen meiner Shellys verwende ich als Stromstrossschalter (aka "Taster") für die Steuerung meines Einfahrtstores zum Grundstück (also "Tor auf"/"Tor zu", je nachdem, ob das Tor offen oder geschlossen ist ändern ein Stromstoss den Zustand des Tores). Das ist also weder "Licht" noch "Steckdose". 
Alle 4 sind shelly1Plus-Geräte.
LG,
Max.
![IMG_3645](https://github.com/digaus/shellyhome-i18n/assets/132902019/514df117-1fed-4da1-a066-09711fd222d3)

**Comment by maxbrunold** [comment]
Ach ja: was bedeutet "eigenständiger Verbrauch"?

**Comment by digaus** [comment]
> Ich konnte meine 4 Shellys nun finden und sie werden unter "vorhandene Geräte" angezeigt.
> Wenn ich versuche sie zur Kategorie "Geräte" hinzuzufügen, dann habe ich aber nur die Option "Räume". Die Aufklappliste bleibt rot und "Geräte" wird nicht als Option angezeigt. Ich würde die Shells aber gerne der Kategorie "Geräte" hinzufügen. Mache ich etwas falsch?
> Beim "Modus" kann ich nur "Schalter" wählen, weitere Optionen werden nicht angezeigt. Bei "Typ" habe ich die Auswahl "Licht" oder "Steckdose".
> Einen meiner Shellys verwende ich als Stromstrossschalter (aka "Taster") für die Steuerung meines Einfahrtstores zum Grundstück (also "Tor auf"/"Tor zu", je nachdem, ob das Tor offen oder geschlossen ist ändern ein Stromstoss den Zustand des Tores). Das ist also weder "Licht" noch "Steckdose".
> Alle 4 sind shelly1Plus-Geräte.
> LG,
> Max.
> ![IMG_3645](https://user-images.githubusercontent.com/132902019/244648617-514df117-1fed-4da1-a066-09711fd222d3.PNG)

Da ich ebenfalls die Geräte mit der Cloud von Shelly synchronisiere (falls man sich mit einem entsprechenden Konto anmelden), muss jeder Shelly einem Raum zugeordnet sein.

Nachher kann man natürlich auch nur den Shelly einzeln aufs Dashboard ziehen oder Shellys einer Gruppe zuweisen.

Modus bietet mehrere Optionen, falls es z.B. ein 2PM (Rolladen oder zwei Schalter) etc. Ist.

Licht oder Steckdose ist lediglich wichtig wenn die Geräte über die Cloud mit Google Home synchronisiert werden. Dementsprechend tauchen diese dort dann als Licht oder als Steckdose (alles andere) auf.

Eigenständiger Verbrauch heißt, dass der Verbrauch nicht in der Gruppen oder Raum Verbrauch mit eingerechnet wird. Macht z.B. Sinn bei einem 3EM.

**Comment by maxbrunold** [comment]
Hmmm... ....nun, ich verwende die App, weil ich eben **nicht** mit irgendeiner cloud syncen möchte. Ganz, im Gegenteil: Genau das möchte ich eben **nicht**. Clouds haben den Nachteil, dass private Daten bei irgendeinem Anbieter liegen und man nicht weiß, wer auf diese Daten Zugriff hat und wofür sie verwendet werden (aka "Big Data"). Ich beschäftige mich seit dem Jahr 2007 mit diesem Thema und habe 10+ Jahre im Providergeschäft gearbeitet. Ich weiß, was da "abgeht". 

Mit so einem "cloud"-Dienst kann ein Admin herrlich sehen wer wann was tut. Licht ein, Licht aus... ...ist der Bewohner zu Hause oder nicht? Was wird gerade eingeschaltet, was ausgeschaltet, was zeigt die Überwachungskamera usw.... ....so entsteht der gläserne Mensch -wobei man den Menschen das auch noch als Vorteil verkauft.

Daher habe ich auch keinen shellyCloud-Account und beabsichtige auch nicht einen solchen anzulegen. Wer Google-Dienste verwendet, der weiß offensichtlich nicht, was da los ist.... ....daher schätze ich Apps, die auch ohne cloud-Dienste funktionieren.

**Comment by digaus** [comment]
Wie gesagt, musst du die Cloud ja nicht nutzen. Die Optionen habe ich dennoch drin gelassen und nicht noch extra raus programmiert.

**Comment by maxbrunold** [comment]
Mir ist wichtig, dass ich nicht dazu gezwungen werde einen cloud-Dienst zu verwenden. Daher ist die App für mich so wertvoll. :-)

**Comment by maxbrunold** [comment]
Ich habe 4 Stück Shelly Plus1 in Betrieb. Mit der Funktion "vorhandene Geräte hinzufügen" konnte ich 3 Geräte finden. Das vierte Gerät wird aber nicht gefunden, obwohl ich es von meinem Mac aus pingen kann und auch die Admin-Oberfläche in Safari erreichbar ist. Mache ich etwas falsch?

Ich fürchte ich habe auch das Dashboard nicht verstanden, es ist mir nicht gelungen meine Geräte ins Dashboard zu bringen. Wenn ich ein Gerät auswähle und dann ins Dashboard ziehen möchte, dann verschwindet der Eintrag einfach wieder...... (?)

**Comment by digaus** [comment]
Via Drag und Drop kann das Gerät auf dem Dashboard platziert werden 

https://youtu.be/zUim9djZ0SQ

**Comment by maxbrunold** [comment]
Der vierte Shelly konnte nun gefunden und hinzugefügt werden. :-)

Ich habe keine Ahnung, wieso das jetzt geklappt hat, da ich nix verändert habe. Alle Shellys haben die aktuelle Firmware und erhalten ihre IP über DHCP, allerdings immer dieselbe IP - habe ich so am DHCP Server eingestellt.

Man kann die Geräte via drag-and-drop auf dem Dashboard platzieren, allerdings muss man dazu zuerst **die Anzahl der Spalten im Dashboard einstellen**. Der Default-Wert ist **0** - und da kann man dann keine Geräte hinzufügen. Als ich den Wert auf 1 gestellt habe, da hat es plötzlich geklappt. Ich habe einige Zeit gebraucht, um das zu verstehen. Default 0 ist vielleicht nicht ideal für neue Benutzer? ;-)

Interessanterweise kommt es vor, dass ein shelly nicht antwortet, obwohl ich eine WLAN-Wolke mit Ubiquiti gebaut habe (kein mesh, sondern alles per Cat-7 verkabelt). Alle WLAN Gräte bei mir zeigen ein gutes Signal an, nur bei den shellys steht oft "poor", selbst wenn der Access Point keine 3 Meter entfernt ist.  Ich bin nicht so ganz überzeugt von der Qualität des WLAN-Chips in den Shellys....

**Comment by digaus** [comment]
Habe auch Unifi APs. Have für die Shellys ein separates Netzwerk und VLAN angelegt welches nur auf 2.4Ghz läuft.

Dann noch Multicast DNS (wird für die schnelle IP Erkennung benutzt) im entsprechenden VLAN aktiviert und es läuft ohne Probleme.

Alle Shellys haben den Status "Ausgezeichnet"
