### ISSUE TITLE
Bildschim bleibt weiss in Windows Version

### ISSUE THREAD

**Issue by AxelArnold** [digaus/shellyhome-i18n#35]
Hallo,

von einem Tag auf den anderen blieb der Bildschim weiss mit Eieruhr (Vers. 2.0.12). Daraufhin habe ich die aktuelle Vers. 2.0.17-1 installiert. Es kommt nun ein "Unhandled Error":
![image](https://github.com/digaus/shellyhome-i18n/assets/70210077/5e431956-f0a1-4d5e-b9b2-017b5062b59e)

any help?

Grüße Axel

**Comment by AxelArnold** [comment]
Die vers. 2.0.12 kommt nun nach Neuinstallation nach einiger Zeit mit dem gewohnten Bildschim.

**Comment by digaus** [comment]
Bitte einmal https://github.com/digaus/shellyhome-i18n/releases/tag/2.2.1 probieren :)
