### ISSUE TITLE
Einbindung von Shellys im  Repeater Mode

### ISSUE THREAD

**Issue by flensburgerdunkel** [digaus/shellyhome-i18n#36]
Hallo Dirk,

die neuen plus-Geräte haben einen Repeater-Modus und die damit verbundenen Geräte sind dann unter der Adresse des Repeaters + Port (fortlaufende Nummer) erreichbar. Leider sind die Geräte damit nicht mehr in der App sichtbar. Nur leider benötige ich diese Repeater-Funktion…

Ich bin super zufrieden mit der App und würde mir diese Funktion sehr wünschen.

Vielen Dank im Voraus und viele Grüße
Stefan

**Comment by digaus** [comment]
![image](https://github.com/digaus/shellyhome-i18n/assets/15358538/f85111ab-2e5e-4fab-a50e-04e0fe8b2028)

Danke für das Feedback. Lokal habe ich es eben umgesetzt. Release folgt dann demnächst.

MfG

**Comment by flensburgerdunkel** [comment]
Hallo Dirk,

ich habe gerade gesehen, dass die Version in meinem App Store (iOS)auf 2.3 steht, aber hier immer noch die Version 2.2.1 aktuell ist. Was ist jetzt richtig? Ist die Repeaterfunktion schon für iOS implementiert?


Vielen Dank für Deine Mühen und die tolle Arbeit, die Du in die App steckst.

Stefan

**Comment by digaus** [comment]
Hallo,

ja sollte bereits unter iOS und Android funktionieren. Habe die Windows Version nur noch nicht aktualisiert.

MfG

**Comment by flensburgerdunkel** [comment]
Hallo Dirk,

Habe es gerade ausprobiert und es funktioniert sehr gut. Vielen Dank für die Implementierung!

Gruß
Stefan
