### ISSUE TITLE
Shelly 1 Gen3 not found 

### ISSUE THREAD

**Issue by kdupke** [digaus/shellyhome-i18n#39]
The app says to mail this, but I assume open an issue is good as well.

I have a new shelly 1 Gen3 which is not found

{"name":"Shelly-220","id":"shelly1g3-5432046ef2d8","mac":"5432046EF2D8","slot":0,"model":"S3SW-001X16EU","gen":3,"fw_id":"20240625-123141/1.3.3-gbdfd9b3","ver":"1.3.3","app":"S1G3","auth_en":true,"auth_domain":"shelly1g3-5432046ef2d8"}

**Comment by digaus** [comment]
Fixed
