### ISSUE TITLE
Shelly Home screen locks

### ISSUE THREAD

**Issue by paul-Rye** [digaus/shellyhome-i18n#5]
Hi, I loved the first few hours, I could see every Shelly status in one view. 

Sadly the splash screen now locks so I canno get into the app. Have rebooted IPhone 10 on latest software.

**Comment by digaus** [comment]
> Hi, I loved the first few hours, I could see every Shelly status in one view.
> 
> Sadly the splash screen now locks so I canno get into the app. Have rebooted IPhone 10 on latest software.

Thats odd, I did not try latest iOS version yet because I mostly use android. When I find time I will check it out.

You can however try to clear the app cache or reinstall it.

**Comment by digaus** [comment]
Should be fixed with 2.x.x
