### ISSUE TITLE
Iphone 11Pro Max wird sehr heiß

### ISSUE THREAD

**Issue by stekaba** [digaus/shellyhome-i18n#6]
Das Gerät wird bei der Nutzung der App reproduzierbar ungewöhnlich heiß. Da stimmt etwas nicht. 
Ansonsten: sehr schöne App, die ich gerne nutzen würde.

**Comment by digaus** [comment]
Beim starten der Anwendung wird ein Scan des Netzwerkes durchgeführt. D.h. die App versucht 250 IP Adressen zu erreichen. Dies kann u.a. lange dauern und erfordert auch viele Ressourcen. Ich arbeite bereits an einer V2, welche viele Verbesserungen und Performance Optimierungen beinhaltet. ETA -> Ende diesen Jahres.
