### ISSUE TITLE
Can’t add Devices

### ISSUE THREAD

**Issue by Solilord** [digaus/shellyhome-i18n#7]
Hey,

I can't add any devices.
My (yet) 2 shellys 2.5 are found.
They are marked as locked.
After i insert my credentials an click unlock, all text in this menu is gone.
![image](https://user-images.githubusercontent.com/8177636/105041906-dd89f480-5a63-11eb-8c36-12ac4d6c9a10.png)

Dark theme and clean Reinstall doesn't help!
Iam using ios14.3

The stock Shelly app is also not usable. Adding doesn't work there as well.

Controlling and login in general does work!
Iobroker Shelly Adapter works as well!

Please help.
Thanks in advance

Florian :)

**Comment by digaus** [comment]
> Hey,
> 
> I can't add any devices.
> My (yet) 2 shellys 2.5 are found.
> They are marked as locked.
> After i insert my credentials an click unlock, all text in this menu is gone.
> ![image](https://user-images.githubusercontent.com/8177636/105041906-dd89f480-5a63-11eb-8c36-12ac4d6c9a10.png)
> 
> Dark theme and clean Reinstall doesn't help!
> Iam using ios14.3
> 
> The stock Shelly app is also not usable. Adding doesn't work there as well.
> 
> Controlling and login in general does work!
> Iobroker Shelly Adapter works as well!
> 
> Please help.
> Thanks in advance
> 
> Florian :)

Hello, what devices do you have? Only Shelly 2.5 or also other devices? Currently working on new version with many fixes and support for more devices.

**Comment by Solilord** [comment]
Only 2x Shelly 2.5 atm.
That's all.

**Comment by digaus** [comment]
this should be fixed with 2.x.x
