### ISSUE TITLE
Shelly app won’t start with iOS 14.6

### ISSUE THREAD

**Issue by dirtyheizer** [digaus/shellyhome-i18n#8]
With iOS Shelly app does no longer start on my iPhone pro 12 . Please let me Have instructions to better support failure analysis.
Thanks in advance

**Comment by digaus** [comment]
I cannot reproduce it on my iPad with 14.6. Will try to get access to an iPhone to test it there

**Comment by dirtyheizer** [comment]
So, reboot did. not help, shutting down the app did not help either.

I did re install now, seems robuster again, which i haven‘t tried earlier,
I will monitor the behavior and let you know once I run into same observation again.
Thanks

**Comment by dirtyheizer** [comment]
Hey
Ran into same issue today again, so seems somehow reproducible, let me know if you need more Details…but here is what I did yesterday after reinstall:
1) created 4x new rooms
2) added 1x Shelly plug and addressed to one of the 4 rooms.
3) pulled/ started app again this morning, ended in circle of death with no negative feedback/popup
(Another reinstall solved it again today)
Thanks

**Comment by digaus** [comment]
Should not happen with version 2.x.x anymore
