### ISSUE TITLE
Add User Field 

### ISSUE THREAD

**Issue by Kalle-sh** [digaus/shellyhome-i18n#9]
Please, can you and a user field to add devices with username and passwort.

**Comment by digaus** [comment]
> Please, can you and a user field to add devices with username and passwort.

You can add devices which are password restriced? When you the device is locked you can click on it and you will be promted to enter the username and password for it.

I am currently still working on version 2 which will also include support for multiple accounts aswell as the new NG devices.

![image](https://user-images.githubusercontent.com/15358538/133926572-a7ffa01c-d7b0-4801-83dd-120b5b095ed9.png)
